### ISSUE TITLE
5月9日左右开始无法获取弹幕 B站，大佬可以修复下吗，感谢你

### ISSUE THREAD

**Issue by PowerDerk** [LuckyPuppy514/Play-With-MPV#149]
5月9日左右开始无法获取弹幕 B站，大佬可以修复下吗，感谢你

**Comment by verygoodlee** [comment]
弹幕应该去这个仓库提[MPV-Play-BiliBili-Comments](https://github.com/itKelis/MPV-Play-BiliBili-Comments)
已经修复但还没合并 itKelis/MPV-Play-BiliBili-Comments#31

**Comment by shmilee** [comment]
命令行运行 `python ~/.config/mpv/scripts/bilibiliAssert/Danmu2Ass.py 1589890104` ，可以获取弹幕文件 bilibili.ass
直接mpv运行也正常。`mpv --ytdl --script-opts-append="cid=1589890104" https://www.bilibili.com/video/BV1D6421Z7Ng/`

**但是** 油猴脚本 这边没把cid传过去。不知道linux自定义播放器如何传cid？
![2024-06-27-021800_680x502_scrot](https://github.com/LuckyPuppy514/Play-With-MPV/assets/2681740/9350b0f8-b29f-48a0-aa79-3224044ed8e1)

```
[bilibiliAssert] 弹幕正在上膛
[bilibiliAssert] DEBUG:  Namespace(directory='~/.config/mpv/scripts/bilibiliAssert', size='1365x768', font='sans-serif', 
fontsize=37.0, alpha=0.95, duration_marquee=10.0, duration_still=5.0, filter=None, filter_file=None, protect=576,
 reduce=True, cid=[''])
[bilibiliAssert] Traceback (most recent call last):
[bilibiliAssert]   File "~/.config/mpv/scripts/bilibiliAssert/Danmu2Ass.py", line 519, in <module>
[bilibiliAssert]     main()
[bilibiliAssert]   File "~/.config/mpv/scripts/bilibiliAssert/Danmu2Ass.py", line 513, in main
[bilibiliAssert]     comments = getComments(args.cid,args.fontsize)
[bilibiliAssert]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by verygoodlee** [comment]
目前自定义播放器没法传cid，代码里写死了，只有mpv会带上cid，自定义播放器不会传
https://github.com/LuckyPuppy514/Play-With-MPV/blob/04a6387b0a0875c36249d5f336a0f4db3a09cf8f/play-with-mpv.user.js#L2022-L2028
不是很理解你为啥mpv还要自定义，没啥必要吧

**Comment by shmilee** [comment]
因为MPV是只考虑了windows平台，即使是设置path=/usr/bin/mpv, 都会修改为mpv.exe。Linux平台只能自定义 https://github.com/LuckyPuppy514/Play-With-MPV/issues/124

本来 MPV-Play-BiliBili-Comments 配合 ytdl可以自动获取cid的, 但这里的脚本传过去的视频地址不是原始的（如下 BV1Tw4m1q7fP），然后main.lua 的 获取 path 也不包含 bilibili.com，所以cid就无法自动找到了？估计是这样。
```bash
$ mpv https://www.bilibili.com/video/BV1Tw4m1q7fP                   

[bilibiliAssert] path=https://www.bilibili.com/video/BV1Tw4m1q7fP, **cid=1570715185**
[bilibiliAssert] 弹幕正在上膛
AO: [pulse] 48000Hz stereo 2ch float
VO: [gpu] 852x480 => 853x480 yuv420p
[bilibiliAssert] DEBUG:  Namespace(directory='~/.config/mpv/scripts/bilibiliAssert', size='2044x1152', font='sans-serif', 
fontsize=37.0, alpha=0.95, duration_marquee=10.0, duration_still=5.0, filter=None, filter_file=None, protect=864, reduce=True, 
cid=['1570715185'])
[bilibiliAssert] 开火
```

Linux 下一个弹幕成功的方案：
416271-play-with-mpv（获取 mpv-debug://play/XXXX/?cookies=www.bilibili.com.txt）
-> mpv-handler （处理 mpv:// 或 mpv-debug://）
-> mpv https://www.bilibili.com/video/BVXXXX（配合 ytdl 和 bilibiliAssert 自动加载弹幕）
DEBUG输出:
```
mpv-debug://play/aHR0cHM6Ly93d3cuYmlsaWJpbGkuY29tL3ZpZGVvL0JWMVI0NDIxRDdhNS8_c3BtX2lkX2Zyb209MzMzLjEwMDcudGlhbm1hLjUtMi0xNS5jbGljayZ2ZF9zb3VyY2U9MTk2YWQxMDY0ZWMwYzU1ZGNiMjQ5MmUxZGM2ZjFjNWM/?cookies=www.bilibili.com.txt


Playing: https://www.bilibili.com/video/BV1R4421D7a5/?spm_id_from=333.1007.tianma.5-2-15.click&vd_source=196ad1064ec0c55dcb2492e1dc6f1c5c
 (+) Video --vid=1 (*) (hevc 1920x1080 25.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
     Subs  --sid=1 --slang=ai-zh 'srt' (null) (external)
     Subs  --sid=2 --slang=danmaku 'xml' (null) (external)
File tags:
 Description: Packed by Bilibili XCoder v2.0.2
 Uploader: 爱音乐的三丈
Track removed:
 (+) Video --vid=1 (*) (hevc 1920x1080 25.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
     Subs  --sid=1 --slang=ai-zh 'srt' (null) (external)
[bilibiliAssert] path=https://www.bilibili.com/video/BV1R4421D7a5/?spm_id_from=333.1007.tianma.5-2-15.click&vd_source=196ad1064ec0c55dcb2492e1dc6f1c5c, cid=1587377545
[bilibiliAssert] 弹幕正在上膛
AO: [pulse] 48000Hz stereo 2ch float
VO: [gpu] 1920x1080 yuv420p
[bilibiliAssert] DEBUG:  Namespace(directory='~/.config/mpv/scripts/bilibiliAssert', size='2048x1152', font='sans-serif', 
fontsize=37.0, alpha=0.95, duration_marquee=10.0, duration_still=5.0, filter=None, filter_file=None, protect=864, reduce=True,
cid=['1587377545'])
[bilibiliAssert] 开火
Track added:
 (+) Video --vid=1 (*) (hevc [Main] 1920x1080 25.000fps)
 (+) Audio --aid=1 (*) (aac [LC] 2ch 48000Hz)
     Subs  --sid=1 --slang=ai-zh 'srt' (null) (external)
     Subs  --sid=2 'bilibili.ass' (ass) (external)
```

**Comment by Tony15246** [comment]
> 命令行运行 `python ~/.config/mpv/scripts/bilibiliAssert/Danmu2Ass.py 1589890104` ，可以获取弹幕文件 bilibili.ass 直接mpv运行也正常。`mpv --ytdl --script-opts-append="cid=1589890104" https://www.bilibili.com/video/BV1D6421Z7Ng/`
> 
> **但是** 油猴脚本 这边没把cid传过去。不知道linux自定义播放器如何传cid？ ![2024-06-27-021800_680x502_scrot](https://private-user-images.githubusercontent.com/2681740/343286769-9350b0f8-b29f-48a0-aa79-3224044ed8e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MjA5ODcsIm5iZiI6MTcyNTgyMDY4NywicGF0aCI6Ii8yNjgxNzQwLzM0MzI4Njc2OS05MzUwYjBmOC1iMjlmLTQ4YTAtYWE3OS0zMjI0MDQ0ZWQ4ZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDhUMTgzODA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGFkMTRjZDI1Y2UxMjRhNTljOGM1NTc4ZjhlODQ4OTE2NjBmNDc4ZWNkMGRiZmJjNWNkMjU1YmZiMDI0YWFjMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lNvpmO0IECN9J9iJKWBp-zusfRK39uRYM8ZsBeW4GTs)
> 
> ```
> [bilibiliAssert] 弹幕正在上膛
> [bilibiliAssert] DEBUG:  Namespace(directory='~/.config/mpv/scripts/bilibiliAssert', size='1365x768', font='sans-serif', 
> fontsize=37.0, alpha=0.95, duration_marquee=10.0, duration_still=5.0, filter=None, filter_file=None, protect=576,
>  reduce=True, cid=[''])
> [bilibiliAssert] Traceback (most recent call last):
> [bilibiliAssert]   File "~/.config/mpv/scripts/bilibiliAssert/Danmu2Ass.py", line 519, in <module>
> [bilibiliAssert]     main()
> [bilibiliAssert]   File "~/.config/mpv/scripts/bilibiliAssert/Danmu2Ass.py", line 513, in main
> [bilibiliAssert]     comments = getComments(args.cid,args.fontsize)
> [bilibiliAssert]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```

有个简单的办法，我就是这么干的，把油猴脚本里面下面这几行代码删了

https://github.com/LuckyPuppy514/Play-With-MPV/blob/04a6387b0a0875c36249d5f336a0f4db3a09cf8f/play-with-mpv.user.js#L2022-L2028

直接改成这两行，强行把cid给进去

```
handler.media.setOther(`--script-opts-append="cid=${cid}" `);
handler.player.params.other = handler.media.other
```

**Comment by shmilee** [comment]
@Tony15246 是个办法，只是脚本自动更新后每次都要改，比较麻烦。

我后来是从 `videoUrl` 直接匹配拿到 `cid`。顺便获取弹幕的py和lua脚本重写了。
因为支持的不止是 LuckyPuppy514/Play-With-MPV的油猴脚本，所以从`videoUrl` 拿cid是fallback的。

https://github.com/shmilee/config-mpv/blob/767d35069cbaa317ed176062b07372a9787e63e2/scripts/danmuku.lua#L354-L363

**Comment by Tony15246** [comment]
> @Tony15246 是个办法，只是脚本自动更新后每次都要改，比较麻烦。
> 
> 我后来是从 `videoUrl` 直接匹配拿到 `cid`。顺便获取弹幕的py和lua脚本重写了。 因为支持的不止是 LuckyPuppy514/Play-With-MPV的油猴脚本，所以从`videoUrl` 拿cid是fallback的。
> 
> https://github.com/shmilee/config-mpv/blob/767d35069cbaa317ed176062b07372a9787e63e2/scripts/danmuku.lua#L354-L363

确实，这样实现跟浏览器插件解耦，更稳定更合理👍
